フレンド一覧からトーク画面への画面遷移
line-school2018summer/fukuoka-a-client pull request #43
Opened 2018-09-13 09:47 UTC by Tokky-tane

issue #41 

##  概要
- フレンド一覧画面で、フレンドかルームをクリックするとトーク画面へ遷移する機能の実装
- ローカルストレージからフレンドとグループを取得する部分のリファクタリング

2018-09-13 10:25 UTC, nanae772 requested changes
friendsとgroupsのフィルターの条件が逆になってる部分さえ直してもらえれば、あとはOKだと思います！

2018-09-13 10:25 UTC, nanae772 commented on android-client/app/src/main/java/com/sample/android_client/FriendsFragment.kt
> +        groups = rooms.filter { !(it.isGroup) }.map { it.toRoomItem() }
ここfilterの条件が逆になっちゃってますね
friendsが!(it.isGroup)で、groupsがit.isGroupですね

2018-09-13 14:01 UTC, Tokky-tane commented
レビューありがとうございます！
修正完了しました😎

2018-09-14 02:00 UTC, nanae772 approved these changes

2018-09-14 02:05 UTC, merged